spring:
    datasource:
        url: jdbc:postgresql:///to_do?cloudSqlInstance=to-do-application-301513:us-central1:to-do-2&socketFactory=com.google.cloud.sql.postgres.SocketFactory&user=postgres&password=codewebs
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect



