spring:
    datasource:
        password: codewebs
        url: jdbc:postgresql://107.178.210.194/to_do
        username: postgres
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect